(() => {
  'use strict';

  const VERSION = '1.8.0';
  const LEGAL_VERSION = '1.0.0';
  const EFFECTIVE_DATE = '2026-08-24';
  const STUDIO = 'Benedict Interactive';
  const SUPPORT_EMAIL = 'benedict.support@gmail.com';
  const KOFI_URL = 'https://ko-fi.com/benedictinteractive';
  const PROMPTPAY_QR_URL = 'https://grolygori789-crypto.github.io/little-ganesha-tarot/assets/support/promptpay-qr.png';
  const RECIPIENT = { en: 'Jakraphan Benjasupanimit', th: 'จักรพันธ์ เบญจศุภนิมิต' };
  const MOTION_KEY = 'velnox.motion';

  const C = {
    en: {
      exp:'Experience', privacy:'Privacy & Data', measurement:'Measurement & Transparency', support:'Support Velnox', help:'Help & Feedback', legal:'Legal & Privacy', aboutGroup:'About Velnox',
      motion:'Motion', motionSub:'Follow your device or reduce interface motion', system:'System', full:'Full', reduced:'Reduced',
      localData:'Local data & privacy', localDataSub:'What stays on this device and what leaves during a test', method:'How Velnox measures', methodSub:'Engine, sampling, confidence and data usage', score:'Score & ranking methodology', scoreSub:'Velnox Score, Country and Worldwide comparison', location:'Network location & VPN note', locationSub:'Country detection without storing raw IP in history',
      supportNote:'Velnox is free to use. Voluntary support helps fund development, testing and benchmark maintenance.', worldwide:'Worldwide support', worldwideSub:'Ko-fi · support Benedict Interactive', thailand:'Thailand support', thailandSub:'PromptPay · scan or open the QR',
      report:'Report a problem', reportSub:'Tell us what happened and optionally include non-sensitive diagnostics', feedback:'Send feedback', feedbackSub:'Share an idea, improvement or experience', diagnostics:'Copy diagnostic info', diagnosticsSub:'App, browser and environment details — no IP or test history',
      legalCenter:'Legal Center', legalSub:'Copyright, Terms of Use, Privacy and third-party notices', legalFoot:'© 2026 Benedict Interactive · All rights reserved.', about:'About Velnox', aboutSub:'Version, sources, privacy and studio information',
      back:'Back', home:'Home', cancel:'Cancel', cont:'Continue', externalTitle:'External destination', externalBody:'You are leaving Velnox. The destination handles its own accounts, payments and privacy practices.',
      transEye:'MEASUREMENT & TRANSPARENCY', transTitle:'Know what Velnox is measuring', transIntro:'Measurements are estimates, rankings are benchmark comparisons, and uncertainty is shown rather than hidden.',
      measureTitle:'How Velnox measures', measure1:'Velnox uses Cloudflare speed-test infrastructure as its primary measurement engine with an accuracy-first sequence: repeated latency checks, progressively larger throughput samples, interleaved latency probes and loaded-latency observations.', measure2:'Fast connections can transfer substantial test data. A full run usually takes around a minute, but duration varies with device, routing and connection conditions. Velnox can time out or cancel instead of inventing a result.', measure3:'Packet loss is intentionally not displayed until Velnox has a reliable measurement path for it. Missing metrics are not inferred.',
      scoreTitle:'Velnox Score', score1:'Velnox Score is a 0–100 heuristic for the measured connection, not a population percentile. Core weighting is Download 35%, Upload 20%, Ping 25% and Jitter 20%, with a bounded loaded-latency penalty when loaded-latency data is available.', score2:'Gold, Silver, Bronze and Needs Attention are product quality tiers. They are separate from Country and Worldwide benchmark standing.',
      rankTitle:'Country & Worldwide ranking', rank1:'Benchmark comparison uses the Velnox Standard Base generated from Cloudflare Radar speed histograms over a rolling 90-day window. Country and Worldwide are separate distributions, so the same connection can rank differently in each.', rank2:'Percentiles are estimates derived from bucketed histogram data. The overall Velnox Benchmark Index is a weighted composite of available metric percentiles, not a census of every internet user.',
      locTitle:'Network location & VPNs', loc1:'Velnox uses the observed network-exit country to select a country benchmark. A VPN or proxy can change that detected country. Velnox does not store your raw IP address in local test history.', loc2:'Country detection is used for benchmark selection and display, not to build an account or personal profile.',
      limitsTitle:'What Velnox does not claim', limits:'Different speed-test providers can report different values because servers, routing, sampling and timing differ. Velnox aims for repeatability, transparent methodology and practical interpretation — not a promise to match another provider’s number.',
      supportEye:'SUPPORT THE PROJECT', supportTitle:'Help keep Velnox independent', supportLead:'Velnox is free to use. If it has been useful, you can support Benedict Interactive through one of these voluntary routes.', worldBody:'Ko-fi handles payment and account details outside Velnox.', thaiBody:'PromptPay support for users in Thailand. Verify the recipient name in your banking app before confirming any transfer.', verify:'Verify recipient', openKofi:'Open Ko-fi', openQr:'Open QR image', optional:'Support is always optional and never changes measurements, rankings, features or access.', thanks:'Thank you for helping fund careful development, testing and future improvements.',
      helpEye:'HELP & FEEDBACK', helpTitle:'Tell us what worked — or what did not', helpLead:'Velnox can prepare an email or copy non-sensitive diagnostics so you stay in control of what is sent.', problemTitle:'Report a problem', feedbackTitle:'Send feedback', message:'Your message', problemPH:'What happened? What were you trying to do?', feedbackPH:'What should Velnox improve or add?', includeDiag:'Include non-sensitive diagnostics', emailNote:'This opens your email app. Nothing is sent until you choose Send there.', openEmail:'Open email', copy:'Copy details', copied:'Copied to clipboard.', copyFail:'Could not copy automatically. Please copy the text manually.', required:'Please write a short message first.',
      legalEye:'LEGAL & PRIVACY', legalTitle:'Legal Center', legalIntro:'Clear product rules for ownership, use, privacy, measurement data and third-party services.', copyright:'Copyright & Intellectual Property', copyrightSub:'Ownership, permitted personal use and reserved rights', terms:'Terms of Use', termsSub:'Rules and limitations for using Velnox', privacyPolicy:'Privacy Policy', privacySub:'Local history, test traffic, benchmark data and external services', third:'Third-Party Notices', thirdSub:'Cloudflare, GitHub Pages and other third-party rights', effective:'Effective', version:'Legal version',
      cpTitle:'Copyright & Intellectual Property', cp1:'Velnox, its original source code, interface design, original graphics, written explanations, product identity and documentation are protected works of Benedict Interactive except where third-party rights or licences apply.', cp2:'Public availability of the website or repository does not by itself grant permission to copy, redistribute, resell, mirror, commercially exploit or create a substantially copied competing product. Ordinary personal, non-commercial screenshots of your own Velnox results are permitted.', cp3:'No exclusive rights are claimed in general networking concepts, facts, standards, public-domain material or third-party software and services.',
      termsTitle:'Terms of Use', terms1:'Velnox provides browser-based network measurements, interpretations and benchmark estimates for informational use. Results are not guarantees of ISP service, application performance, contractual speed or future network behaviour.', terms2:'You may use the released application for ordinary personal or organisational network checking. Do not deliberately misrepresent measurements, impersonate Benedict Interactive, interfere with the service, bypass security controls, or unlawfully exploit protected code or assets.', terms3:'The service may change, be unavailable, or depend on third-party infrastructure. Nothing here removes rights that applicable law does not allow to be waived or limited.',
      ppTitle:'Privacy Policy', pp1:'Velnox does not require an account. When Save History is enabled, saved test history is stored in browser LocalStorage on the current device/browser profile. Clearing history removes that local Velnox history.', pp2:'A speed test necessarily sends test traffic to Cloudflare speed-test endpoints. Velnox may use Cloudflare-provided network metadata or browser locale to estimate the network-exit country for benchmark selection. Velnox does not put a raw IP address into local test history.', pp3:'Country and Worldwide benchmark files are aggregated Cloudflare Radar datasets generated by the Velnox benchmark workflow. They are not personal histories. Ko-fi, PromptPay support assets, GitHub Pages and email applications are third-party services with their own practices.', pp4:'Velnox V1.8 contains no advertising system, cross-site behavioural advertising tracker, or system for selling user data.',
      tpTitle:'Third-Party Notices', tp1:'Cloudflare: Velnox uses Cloudflare speed-test infrastructure for primary browser measurements and Cloudflare Radar histogram data for the Velnox Standard Base. Cloudflare services, trademarks, data and software remain subject to Cloudflare’s applicable terms and licences.', tp2:'GitHub Pages: the public Velnox website is hosted through GitHub Pages. GitHub controls the hosting platform and its platform-level logs, security and availability.', tp3:'Ko-fi and PromptPay: voluntary support routes are external to the Velnox measurement engine. Payment details and account handling occur outside Velnox. Third-party names and marks belong to their respective owners.',
      aboutEye:'ABOUT', aboutTitle:'Velnox — Network Intelligence', aboutLead:'A privacy-conscious network-health assistant by Benedict Interactive.', versionLabel:'Version', studio:'Studio', primary:'Primary measurement', benchmark:'Benchmark source', hosting:'Hosting', privacyModel:'Privacy model', sourceStatus:'Source status', primaryV:'@cloudflare/speedtest 1.13.0 · accuracy-first profile', benchmarkV:'Cloudflare Radar · rolling 90-day histograms', hostingV:'GitHub Pages', privacyV:'No account · optional local history · no raw IP stored in history', sourceV:'Free to use · proprietary source unless separately licensed', aboutNote:'Measure → Interpret → Compare → Diagnose → Recommend → Retest, with uncertainty and source limitations shown instead of hidden.'
    },
    th: {
      exp:'ประสบการณ์ใช้งาน', privacy:'ความเป็นส่วนตัวและข้อมูล', measurement:'การวัดและความโปร่งใส', support:'สนับสนุน Velnox', help:'ช่วยเหลือและข้อเสนอแนะ', legal:'กฎหมายและความเป็นส่วนตัว', aboutGroup:'เกี่ยวกับ Velnox',
      motion:'การเคลื่อนไหว', motionSub:'ใช้ตามการตั้งค่าเครื่อง หรือลดการเคลื่อนไหวของหน้าจอ', system:'ตามระบบ', full:'เต็ม', reduced:'ลดลง',
      localData:'ข้อมูลในเครื่องและความเป็นส่วนตัว', localDataSub:'ดูว่าข้อมูลใดอยู่ในอุปกรณ์ และข้อมูลใดออกไปเมื่อทดสอบ', method:'Velnox วัดอย่างไร', methodSub:'Engine, การเก็บตัวอย่าง, ความเชื่อมั่น และการใช้ข้อมูล', score:'วิธีคิดคะแนนและอันดับ', scoreSub:'Velnox Score, ประเทศ และทั่วโลก', location:'ตำแหน่งเครือข่ายและ VPN', locationSub:'ตรวจประเทศอย่างไรโดยไม่เก็บ raw IP ในประวัติ',
      supportNote:'Velnox เปิดให้ใช้ฟรี การสนับสนุนโดยสมัครใจช่วยค่าใช้จ่ายในการพัฒนา ทดสอบ และดูแลฐาน Benchmark', worldwide:'สนับสนุนจากทั่วโลก', worldwideSub:'Ko-fi · สนับสนุน Benedict Interactive', thailand:'สนับสนุนในประเทศไทย', thailandSub:'PromptPay · สแกนหรือเปิด QR',
      report:'รายงานปัญหา', reportSub:'บอกว่าเกิดอะไรขึ้น และเลือกแนบข้อมูลวินิจฉัยที่ไม่ละเอียดอ่อนได้', feedback:'ส่งข้อเสนอแนะ', feedbackSub:'เสนอไอเดีย สิ่งที่ควรปรับ หรือประสบการณ์ใช้งาน', diagnostics:'คัดลอกข้อมูลวินิจฉัย', diagnosticsSub:'ข้อมูลแอป เบราว์เซอร์ และสภาพแวดล้อม — ไม่รวม IP หรือประวัติทดสอบ',
      legalCenter:'ศูนย์ข้อมูลทางกฎหมาย', legalSub:'ลิขสิทธิ์ ข้อกำหนดการใช้งาน ความเป็นส่วนตัว และบุคคลที่สาม', legalFoot:'© 2026 Benedict Interactive · สงวนสิทธิ์ตามกฎหมาย', about:'เกี่ยวกับ Velnox', aboutSub:'เวอร์ชัน แหล่งข้อมูล ความเป็นส่วนตัว และข้อมูลสตูดิโอ',
      back:'ย้อนกลับ', home:'หน้าหลัก', cancel:'ยกเลิก', cont:'ดำเนินการต่อ', externalTitle:'กำลังไปยังเว็บไซต์ภายนอก', externalBody:'คุณกำลังออกจาก Velnox ปลายทางจะจัดการบัญชี การชำระเงิน และนโยบายความเป็นส่วนตัวของตนเอง',
      transEye:'การวัดและความโปร่งใส', transTitle:'รู้ว่า Velnox กำลังวัดอะไร', transIntro:'ผลวัดเป็นค่าประมาณ อันดับเป็นการเทียบ Benchmark และความไม่แน่นอนจะถูกแสดงแทนการซ่อน',
      measureTitle:'Velnox วัดอย่างไร', measure1:'Velnox ใช้โครงสร้าง Speed Test ของ Cloudflare เป็น engine หลัก ด้วยลำดับการวัดแบบเน้นความแม่นยำ ได้แก่การวัด latency ซ้ำ การเพิ่มขนาดตัวอย่าง throughput เป็นลำดับ การแทรก latency ระหว่างช่วงวัด และการดู loaded latency', measure2:'เน็ตเร็วอาจใช้ข้อมูลทดสอบค่อนข้างมาก การทดสอบเต็มรูปแบบมักใช้เวลาประมาณหนึ่งนาที แต่ขึ้นกับอุปกรณ์ เส้นทางเครือข่าย และสภาพการเชื่อมต่อ ระบบสามารถ timeout หรือยกเลิกได้ แทนที่จะสร้างผลขึ้นมาเอง', measure3:'Velnox ตั้งใจไม่แสดง Packet Loss จนกว่าจะมีวิธีวัดที่เชื่อถือได้ และจะไม่เดาค่าที่ไม่มีการวัดจริง',
      scoreTitle:'Velnox Score', score1:'Velnox Score เป็นคะแนน heuristic 0–100 ของการเชื่อมต่อที่วัดในครั้งนั้น ไม่ใช่ percentile ของประชากร น้ำหนักหลักคือ Download 35%, Upload 20%, Ping 25% และ Jitter 20% พร้อม bounded penalty จาก loaded latency เมื่อมีข้อมูล', score2:'Gold, Silver, Bronze และ Needs Attention เป็นระดับคุณภาพของผลิตภัณฑ์ แยกจากอันดับ Country และ Worldwide',
      rankTitle:'อันดับประเทศและทั่วโลก', rank1:'การเปรียบเทียบใช้ Velnox Standard Base ที่สร้างจาก histogram ของ Cloudflare Radar ในหน้าต่างย้อนหลัง 90 วัน ประเทศและทั่วโลกเป็นคนละ distribution จึงสามารถได้อันดับต่างกัน', rank2:'Percentile เป็นค่าประมาณจาก bucketed histogram ส่วน Velnox Benchmark Index เป็น composite จาก percentile ของ metric ที่มี ไม่ใช่การสำรวจผู้ใช้อินเทอร์เน็ตทุกคนบนโลก',
      locTitle:'ตำแหน่งเครือข่ายและ VPN', loc1:'Velnox ใช้ประเทศของ network exit เพื่อเลือก Benchmark ประเทศ VPN หรือ proxy สามารถทำให้ประเทศที่ตรวจพบเปลี่ยนไป แอปไม่เก็บ raw IP ไว้ในประวัติผลทดสอบ', loc2:'ข้อมูลประเทศใช้เพื่อเลือก Benchmark และแสดงผลเท่านั้น ไม่ได้ใช้สร้างบัญชีหรือโปรไฟล์ส่วนตัว',
      limitsTitle:'สิ่งที่ Velnox ไม่อ้าง', limits:'ผู้ให้บริการ Speed Test ต่างกันสามารถรายงานตัวเลขต่างกันได้ เพราะ server, routing, sampling และ timing ต่างกัน Velnox เน้นความทำซ้ำได้ วิธีวัดที่อธิบายได้ และการแปลผลที่มีประโยชน์ ไม่ได้สัญญาว่าจะตรงกับผู้ให้บริการรายอื่น',
      supportEye:'สนับสนุนโปรเจกต์', supportTitle:'ช่วยให้ Velnox พัฒนาต่ออย่างอิสระ', supportLead:'Velnox เปิดให้ใช้ฟรี ถ้าแอปมีประโยชน์ สามารถสนับสนุน Benedict Interactive ผ่านช่องทางโดยสมัครใจได้', worldBody:'Ko-fi จัดการบัญชีและการชำระเงินภายนอก Velnox', thaiBody:'PromptPay สำหรับผู้ใช้ในประเทศไทย กรุณาตรวจสอบชื่อผู้รับในแอปธนาคารก่อนยืนยันทุกครั้ง', verify:'ตรวจสอบชื่อผู้รับ', openKofi:'เปิด Ko-fi', openQr:'เปิดภาพ QR', optional:'การสนับสนุนเป็นทางเลือกเสมอ และไม่มีผลต่อผลวัด อันดับ ฟีเจอร์ หรือสิทธิ์การใช้งาน', thanks:'ขอบคุณที่ช่วยสนับสนุนการพัฒนา การทดสอบ และการปรับปรุง Velnox ต่อไป',
      helpEye:'ช่วยเหลือและข้อเสนอแนะ', helpTitle:'บอกเราได้เลยว่าส่วนไหนเวิร์ก — หรือไม่เวิร์ก', helpLead:'Velnox สามารถเตรียมอีเมลหรือคัดลอกข้อมูลวินิจฉัยที่ไม่ละเอียดอ่อน โดยผู้ใช้เป็นคนตัดสินใจเองว่าจะส่งอะไร', problemTitle:'รายงานปัญหา', feedbackTitle:'ส่งข้อเสนอแนะ', message:'ข้อความของคุณ', problemPH:'เกิดอะไรขึ้น และตอนนั้นคุณกำลังทำอะไรอยู่?', feedbackPH:'อยากให้ Velnox ปรับหรือเพิ่มอะไร?', includeDiag:'แนบข้อมูลวินิจฉัยที่ไม่ละเอียดอ่อน', emailNote:'ระบบจะเปิดแอปอีเมล และยังไม่มีข้อมูลถูกส่งจนกว่าคุณจะกดส่งเอง', openEmail:'เปิดอีเมล', copy:'คัดลอกรายละเอียด', copied:'คัดลอกแล้ว', copyFail:'คัดลอกอัตโนมัติไม่สำเร็จ กรุณาคัดลอกข้อความด้วยตนเอง', required:'กรุณาเขียนข้อความสั้นๆ ก่อน',
      legalEye:'กฎหมายและความเป็นส่วนตัว', legalTitle:'ศูนย์ข้อมูลทางกฎหมาย', legalIntro:'ขอบเขตสิทธิ์ การใช้งาน ความเป็นส่วนตัว ข้อมูลการวัด และบริการของบุคคลที่สาม อธิบายตามการทำงานจริงของ Velnox', copyright:'ลิขสิทธิ์และทรัพย์สินทางปัญญา', copyrightSub:'กรรมสิทธิ์ การใช้ส่วนตัวที่อนุญาต และสิทธิ์ที่สงวนไว้', terms:'ข้อกำหนดการใช้งาน', termsSub:'กติกาและข้อจำกัดในการใช้ Velnox', privacyPolicy:'นโยบายความเป็นส่วนตัว', privacySub:'ประวัติในเครื่อง Test traffic, Benchmark และบริการภายนอก', third:'ข้อมูลบุคคลที่สาม', thirdSub:'Cloudflare, GitHub Pages และสิทธิ์ของผู้ให้บริการอื่น', effective:'มีผลตั้งแต่', version:'เวอร์ชันเอกสาร',
      cpTitle:'ลิขสิทธิ์และทรัพย์สินทางปัญญา', cp1:'Velnox รวมถึง source code ต้นฉบับ การออกแบบหน้าจอ กราฟิกต้นฉบับ คำอธิบาย เอกลักษณ์ผลิตภัณฑ์ และเอกสาร เป็นงานที่ได้รับความคุ้มครองของ Benedict Interactive เว้นแต่ส่วนที่มีสิทธิ์หรือใบอนุญาตของบุคคลที่สาม', cp2:'การที่เว็บไซต์หรือ repository เปิดให้มองเห็น ไม่ได้หมายถึงได้รับอนุญาตให้นำไปคัดลอก แจกจ่าย ขาย ทำ mirror ใช้เชิงพาณิชย์ หรือสร้างผลิตภัณฑ์คู่แข่งที่คัดลอกอย่างมีนัยสำคัญ อนุญาตให้เก็บหรือแชร์ screenshot ผล Velnox ของตนเองเพื่อการส่วนตัวที่ไม่ใช่เชิงพาณิชย์', cp3:'Velnox ไม่อ้างสิทธิ์แต่เพียงผู้เดียวเหนือแนวคิดเครือข่ายทั่วไป ข้อเท็จจริง มาตรฐาน งานสาธารณสมบัติ ซอฟต์แวร์ หรือบริการของบุคคลที่สาม',
      termsTitle:'ข้อกำหนดการใช้งาน', terms1:'Velnox ให้บริการการวัดเครือข่ายผ่านเบราว์เซอร์ การแปลผล และ Benchmark เพื่อให้ข้อมูล ผลลัพธ์ไม่ใช่การรับประกันบริการ ISP ประสิทธิภาพของทุกแอป ความเร็วตามสัญญา หรือพฤติกรรมเครือข่ายในอนาคต', terms2:'สามารถใช้แอปที่เผยแพร่เพื่อการตรวจสอบเครือข่ายทั่วไปได้ ห้ามบิดเบือนผล แอบอ้างเป็น Benedict Interactive รบกวนระบบ ข้ามมาตรการความปลอดภัย หรือใช้โค้ด/ทรัพย์สินที่ได้รับการคุ้มครองโดยมิชอบ', terms3:'บริการอาจเปลี่ยนแปลง หยุดให้บริการชั่วคราว หรือขึ้นกับโครงสร้างพื้นฐานของบุคคลที่สาม และไม่ตัดสิทธิ์ที่กฎหมายไม่อนุญาตให้สละหรือจำกัด',
      ppTitle:'นโยบายความเป็นส่วนตัว', pp1:'Velnox ไม่ต้องสมัครบัญชี เมื่อเปิด Save History ผลทดสอบที่บันทึกจะอยู่ใน browser LocalStorage ของอุปกรณ์/browser profile ปัจจุบัน การล้างประวัติจะลบประวัติ Velnox ที่เก็บในเครื่องนั้น', pp2:'Speed Test จำเป็นต้องส่ง test traffic ไปยัง endpoint ของ Cloudflare Velnox อาจใช้ network metadata ที่ Cloudflare ให้หรือ browser locale เพื่อประมาณประเทศของ network exit สำหรับเลือก Benchmark และไม่บันทึก raw IP ลงในประวัติภายในเครื่อง', pp3:'ไฟล์ Benchmark ประเทศและทั่วโลกเป็นข้อมูลรวมจาก Cloudflare Radar ที่สร้างผ่าน workflow ของ Velnox ไม่ใช่ประวัติส่วนบุคคล Ko-fi, PromptPay, GitHub Pages และแอปอีเมลเป็นบริการภายนอกที่มีแนวทางของตนเอง', pp4:'Velnox V1.8 ไม่มีระบบโฆษณา ระบบ cross-site behavioural advertising tracking หรือระบบขายข้อมูลผู้ใช้',
      tpTitle:'ข้อมูลบุคคลที่สาม', tp1:'Cloudflare: Velnox ใช้โครงสร้าง Speed Test ของ Cloudflare สำหรับการวัดหลัก และใช้ข้อมูล histogram จาก Cloudflare Radar สำหรับ Velnox Standard Base บริการ เครื่องหมาย ข้อมูล และซอฟต์แวร์ของ Cloudflare อยู่ภายใต้สิทธิ์และเงื่อนไขของ Cloudflare', tp2:'GitHub Pages: เว็บไซต์สาธารณะของ Velnox โฮสต์ผ่าน GitHub Pages โดย GitHub ควบคุมแพลตฟอร์ม hosting, platform logs, security และ availability', tp3:'Ko-fi และ PromptPay: เป็นช่องทางสนับสนุนโดยสมัครใจ แยกจาก measurement engine การชำระเงินและข้อมูลบัญชีดำเนินการภายนอก Velnox ชื่อและเครื่องหมายของบุคคลที่สามเป็นของเจ้าของแต่ละราย',
      aboutEye:'เกี่ยวกับแอป', aboutTitle:'Velnox — Network Intelligence', aboutLead:'ผู้ช่วยวิเคราะห์สุขภาพเครือข่ายที่ให้ความสำคัญกับความเป็นส่วนตัว โดย Benedict Interactive', versionLabel:'เวอร์ชัน', studio:'สตูดิโอ', primary:'การวัดหลัก', benchmark:'แหล่ง Benchmark', hosting:'Hosting', privacyModel:'รูปแบบความเป็นส่วนตัว', sourceStatus:'สถานะ Source', primaryV:'@cloudflare/speedtest 1.13.0 · accuracy-first profile', benchmarkV:'Cloudflare Radar · histogram ย้อนหลัง 90 วัน', hostingV:'GitHub Pages', privacyV:'ไม่ต้องสมัครบัญชี · ประวัติในเครื่องเป็นทางเลือก · ไม่เก็บ raw IP ในประวัติ', sourceV:'ใช้งานฟรี · source เป็น proprietary เว้นแต่ระบุ license แยก', aboutNote:'Measure → Interpret → Compare → Diagnose → Recommend → Retest พร้อมแสดงความไม่แน่นอนและข้อจำกัดของแหล่งข้อมูลอย่างตรงไปตรงมา'
    }
  };

  const S = { root:null, view:'about', focus:null, built:false };
  const isThai = () => { if (document.getElementById('sheetTh')?.classList.contains('active') || document.getElementById('langTh')?.classList.contains('active')) return true; try { return (localStorage.getItem('velnox.lang') || '') === 'th'; } catch { return false; } };
  const L = () => isThai() ? 'th' : 'en';
  const t = k => C[L()][k] ?? C.en[k] ?? k;
  const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function toast(msg){const n=document.getElementById('toast');if(!n)return;n.textContent=msg;n.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.classList.remove('show'),2600)}
  function group(title){const s=document.createElement('section');s.className='trust-settings-group';s.innerHTML=`<h4>${esc(title)}</h4>`;return s}
  function link(id,title,sub,mark='›'){const b=document.createElement('button');b.type='button';b.id=id;b.className='trust-setting-link';b.innerHTML=`<span><strong>${esc(title)}</strong><small>${esc(sub)}</small></span><i aria-hidden="true">${esc(mark)}</i>`;return b}
  function motionRow(){const r=document.createElement('div');r.className='setting-row trust-motion-row';r.innerHTML=`<div><b>${esc(t('motion'))}</b><small>${esc(t('motionSub'))}</small></div><select id="velnoxMotionSelect" class="trust-select" aria-label="${esc(t('motion'))}"><option value="system">${esc(t('system'))}</option><option value="full">${esc(t('full'))}</option><option value="reduced">${esc(t('reduced'))}</option></select>`;return r}
  function applyMotion(v){v=['system','full','reduced'].includes(v)?v:'system';document.documentElement.dataset.velnoxMotion=v;try{localStorage.setItem(MOTION_KEY,v)}catch{}}

  function buildSettings(){
    const sheet=document.getElementById('settingsSheet'); if(!sheet||S.built)return;
    const rows=[...sheet.querySelectorAll(':scope > .setting-row')], clear=document.getElementById('clearHistoryBtn'), about=sheet.querySelector(':scope > .about-box'), head=sheet.querySelector('.sheet-head'), handle=sheet.querySelector('.sheet-handle');
    if(rows.length<5||!clear||!about||!head)return;
    const [languageRow,fullscreenRow,historyRow,techRow,soundRow]=rows;
    const frag=document.createDocumentFragment();
    const g1=group(t('exp')); g1.append(languageRow,fullscreenRow,motionRow(),soundRow); frag.append(g1);
    const g2=group(t('privacy')); g2.append(historyRow,clear,link('trustLocalDataBtn',t('localData'),t('localDataSub'),'◇')); frag.append(g2);
    const g3=group(t('measurement')); g3.append(techRow,link('trustMethodBtn',t('method'),t('methodSub'),'≡'),link('trustScoreBtn',t('score'),t('scoreSub'),'◎'),link('trustLocationBtn',t('location'),t('locationSub'),'⌖')); frag.append(g3);
    const g4=group(t('support')); const note=document.createElement('p');note.className='trust-settings-note';note.textContent=t('supportNote');g4.append(note,link('trustKofiBtn',t('worldwide'),t('worldwideSub'),'↗'),link('trustPromptPayBtn',t('thailand'),t('thailandSub'),'↗'));frag.append(g4);
    const g5=group(t('help'));g5.append(link('trustReportBtn',t('report'),t('reportSub')),link('trustFeedbackBtn',t('feedback'),t('feedbackSub')),link('trustDiagnosticsBtn',t('diagnostics'),t('diagnosticsSub'),'⧉'));frag.append(g5);
    const g6=group(t('legal'));g6.append(link('trustLegalBtn',t('legalCenter'),t('legalSub'),'§'));const foot=document.createElement('p');foot.className='trust-legal-foot';foot.textContent=t('legalFoot');g6.append(foot);frag.append(g6);
    const g7=group(t('aboutGroup'));g7.append(link('trustAboutBtn',t('about'),t('aboutSub'),'i'),about);frag.append(g7);
    for(const ch of [...sheet.children]) if(ch!==handle&&ch!==head)ch.remove(); sheet.append(frag); sheet.classList.add('trust-settings-upgraded'); S.built=true;
    const sel=document.getElementById('velnoxMotionSelect');let m='system';try{m=localStorage.getItem(MOTION_KEY)||'system'}catch{}sel.value=['system','full','reduced'].includes(m)?m:'system';applyMotion(sel.value);sel.addEventListener('change',()=>applyMotion(sel.value));
    document.getElementById('trustLocalDataBtn')?.addEventListener('click',()=>open('transparency','location'));
    document.getElementById('trustMethodBtn')?.addEventListener('click',()=>open('transparency','measure'));
    document.getElementById('trustScoreBtn')?.addEventListener('click',()=>open('transparency','score'));
    document.getElementById('trustLocationBtn')?.addEventListener('click',()=>open('transparency','location'));
    document.getElementById('trustKofiBtn')?.addEventListener('click',()=>open('support','worldwide'));
    document.getElementById('trustPromptPayBtn')?.addEventListener('click',()=>open('support','thailand'));
    document.getElementById('trustReportBtn')?.addEventListener('click',()=>open('help','report'));
    document.getElementById('trustFeedbackBtn')?.addEventListener('click',()=>open('help','feedback'));
    document.getElementById('trustDiagnosticsBtn')?.addEventListener('click',copyDiagnostics);
    document.getElementById('trustLegalBtn')?.addEventListener('click',()=>open('legal'));
    document.getElementById('trustAboutBtn')?.addEventListener('click',()=>open('about'));
  }

  function ensureRoot(){if(S.root)return S.root;const r=document.createElement('section');r.id='trustScreen';r.className='trust-screen';r.hidden=true;r.setAttribute('role','dialog');r.setAttribute('aria-modal','true');r.innerHTML='<header class="trust-topbar"><button id="trustBack" type="button" aria-label="Back">‹</button><div class="trust-brand-lockup"><img class="velnox-brand-mark velnox-brand-mark--trust" src="assets/velnox-mark.svg" alt="" aria-hidden="true"><div><strong>VELNOX</strong><small>NETWORK INTELLIGENCE</small></div></div><button id="trustHome" type="button" aria-label="Home">⌂</button></header><main id="trustContent" class="trust-scroll"></main>';document.getElementById('app')?.appendChild(r);r.querySelector('#trustBack').addEventListener('click',close);r.querySelector('#trustHome').addEventListener('click',()=>close({home:true}));r.addEventListener('click',rootClick);r.addEventListener('error',e=>{if(e.target.matches?.('.trust-qr-wrap img')){e.target.hidden=true;e.target.closest('.trust-qr-wrap')?.classList.add('qr-unavailable')}},true);S.root=r;return r}
  function show(){const r=ensureRoot();S.focus=document.activeElement;document.getElementById('settingsSheet')?.classList.remove('show');document.getElementById('sheetBackdrop')?.classList.remove('show');document.body.classList.add('trust-screen-open');r.hidden=false;requestAnimationFrame(()=>r.classList.add('is-visible'))}
  function close({home=false}={}){if(!S.root||S.root.hidden)return;const r=S.root;r.classList.remove('is-visible');const done=()=>{r.hidden=true;document.body.classList.remove('trust-screen-open');if(home)document.getElementById('homeBtn')?.click();else if(S.focus instanceof HTMLElement&&document.contains(S.focus))S.focus.focus({preventScroll:true});S.focus=null};if(document.documentElement.dataset.velnoxMotion==='reduced'||matchMedia('(prefers-reduced-motion: reduce)').matches)done();else setTimeout(done,180)}
  const block=(id,title,ps)=>`<section class="trust-doc-section" id="trust-${esc(id)}"><h2>${esc(title)}</h2>${ps.map(p=>`<p>${esc(p)}</p>`).join('')}</section>`;
  function transparency(a=''){return `<section class="trust-hero"><span>${esc(t('transEye'))}</span><h1>${esc(t('transTitle'))}</h1><p>${esc(t('transIntro'))}</p></section><div class="trust-principles"><article><i>01</i><b>Measured</b><small>${L()==='th'?'วัดจริง ไม่สร้างค่าที่ไม่มี':'Measured values, no invented metrics'}</small></article><article><i>02</i><b>Estimated</b><small>${L()==='th'?'อันดับระบุว่าเป็นค่าประมาณ':'Benchmark standing is labelled estimated'}</small></article><article><i>03</i><b>Transparent</b><small>${L()==='th'?'บอกข้อจำกัดและแหล่งข้อมูล':'Sources and limitations are disclosed'}</small></article></div><article class="trust-document">${block('measure',t('measureTitle'),[t('measure1'),t('measure2'),t('measure3')])}${block('score',t('scoreTitle'),[t('score1'),t('score2')])}${block('ranking',t('rankTitle'),[t('rank1'),t('rank2')])}${block('location',t('locTitle'),[t('loc1'),t('loc2')])}${block('limits',t('limitsTitle'),[t('limits')])}</article><span data-anchor="${esc(a)}"></span>`}
  function support(a=''){const qr=PROMPTPAY_QR_URL;return `<section class="trust-hero"><span>${esc(t('supportEye'))}</span><h1>${esc(t('supportTitle'))}</h1><p>${esc(t('supportLead'))}</p></section><div class="trust-support-cards"><article class="trust-support-card" id="trust-worldwide"><span class="trust-badge">WORLDWIDE</span><h2>${esc(t('worldwide'))}</h2><p>${esc(t('worldBody'))}</p><button type="button" data-external="${esc(KOFI_URL)}">${esc(t('openKofi'))}<i>↗</i></button></article><article class="trust-support-card trust-support-card--thai" id="trust-thailand"><span class="trust-badge">THAILAND</span><h2>${esc(t('thailand'))}</h2><p>${esc(t('thaiBody'))}</p><div class="trust-qr-wrap"><img src="${esc(qr)}" alt="PromptPay QR" loading="lazy" referrerpolicy="no-referrer"><div><small>${esc(t('verify'))}</small><strong>${esc(RECIPIENT[L()])}</strong></div></div><button type="button" data-external="${esc(qr)}">${esc(t('openQr'))}<i>↗</i></button></article></div><p class="trust-center-note">${esc(t('optional'))}</p><p class="trust-thanks">${esc(t('thanks'))}</p><span data-anchor="${esc(a)}"></span>`}
  function diagnostics(){const ua=navigator.userAgent||'';const platform=/Android/i.test(ua)?'Android':/iPhone|iPad|iPod/i.test(ua)?'iOS/iPadOS':/Windows/i.test(ua)?'Windows':/Macintosh|Mac OS X/i.test(ua)?'macOS':/Linux/i.test(ua)?'Linux':navigator.platform||'Unknown';const m=(re,name)=>{const x=ua.match(re);return x?`${name} ${x[1]}`:null};const browser=m(/SamsungBrowser\/(\d+)/i,'Samsung Internet')||m(/EdgA?\/(\d+)/i,'Edge')||m(/Chrome\/(\d+)/i,'Chrome')||m(/Firefox\/(\d+)/i,'Firefox')||m(/Version\/(\d+).*Safari/i,'Safari')||'Unknown';const mode=matchMedia('(display-mode: fullscreen)').matches?'Installed PWA (fullscreen)':matchMedia('(display-mode: standalone)').matches||navigator.standalone===true?'Installed PWA':document.fullscreenElement?'Browser fullscreen':'Browser / in-app browser';return ['App: Velnox — Network Intelligence',`Version: ${VERSION}`,`Language: ${L()}`,`Platform: ${platform}`,`Browser: ${browser}`,`Environment: ${mode}`,`Online: ${navigator.onLine?'yes':'no'}`,`Viewport: ${innerWidth}x${innerHeight}`,`Service worker: ${navigator.serviceWorker?.controller?'controlled':'not controlled'}`,`Time: ${new Date().toISOString()}`].join('\n')}
  async function copyText(text){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true}}catch{}const a=document.createElement('textarea');a.value=text;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();let ok=false;try{ok=document.execCommand('copy')}catch{}a.remove();return ok}
  async function copyDiagnostics(){toast(await copyText(diagnostics())?t('copied'):t('copyFail'))}
  function help(type='report'){const rep=type!=='feedback';return `<section class="trust-hero"><span>${esc(t('helpEye'))}</span><h1>${esc(t('helpTitle'))}</h1><p>${esc(t('helpLead'))}</p></section><form id="trustFeedbackForm" class="trust-feedback-form" data-type="${rep?'report':'feedback'}"><h2>${esc(rep?t('problemTitle'):t('feedbackTitle'))}</h2><label><span>${esc(t('message'))}</span><textarea id="trustMessage" maxlength="1200" placeholder="${esc(rep?t('problemPH'):t('feedbackPH'))}"></textarea></label><label class="trust-check"><input id="trustIncludeDiagnostics" type="checkbox" checked><span>${esc(t('includeDiag'))}</span></label><p>${esc(t('emailNote'))}</p><div class="trust-action-row"><button type="button" data-copy-report>${esc(t('copy'))}</button><button class="primary" type="submit">${esc(t('openEmail'))}</button></div></form>`}
  function reportBody(type,msg,include){const title=type==='report'?'Velnox — Problem Report':'Velnox — Feedback';const p=[title,'','Message:',msg.trim()];if(include)p.push('','Technical details:',diagnostics());p.push('','---',`Prepared locally. Send voluntarily to ${SUPPORT_EMAIL}.`);return p.join('\n')}
  function legalHome(){return `<section class="trust-hero"><span>${esc(t('legalEye'))}</span><h1>${esc(t('legalTitle'))}</h1><p>${esc(t('legalIntro'))}</p><div class="trust-meta"><span>${esc(t('version'))} ${LEGAL_VERSION}</span><span>${esc(t('effective'))} ${EFFECTIVE_DATE}</span></div></section><div class="trust-legal-cards"><button data-legal-doc="copyright"><i>©</i><span><b>${esc(t('copyright'))}</b><small>${esc(t('copyrightSub'))}</small></span><em>›</em></button><button data-legal-doc="terms"><i>§</i><span><b>${esc(t('terms'))}</b><small>${esc(t('termsSub'))}</small></span><em>›</em></button><button data-legal-doc="privacy"><i>◇</i><span><b>${esc(t('privacyPolicy'))}</b><small>${esc(t('privacySub'))}</small></span><em>›</em></button><button data-legal-doc="third"><i>◈</i><span><b>${esc(t('third'))}</b><small>${esc(t('thirdSub'))}</small></span><em>›</em></button></div><p class="trust-center-note">${esc(t('legalFoot'))}</p>`}
  function legalDoc(id){const map={copyright:[t('cpTitle'),[t('cp1'),t('cp2'),t('cp3')]],terms:[t('termsTitle'),[t('terms1'),t('terms2'),t('terms3')]],privacy:[t('ppTitle'),[t('pp1'),t('pp2'),t('pp3'),t('pp4')]],third:[t('tpTitle'),[t('tp1'),t('tp2'),t('tp3')]]};const [title,ps]=map[id]||map.copyright;return `<section class="trust-hero"><span>${esc(t('legalEye'))}</span><h1>${esc(title)}</h1><div class="trust-meta"><span>${esc(t('version'))} ${LEGAL_VERSION}</span><span>${esc(t('effective'))} ${EFFECTIVE_DATE}</span></div></section><article class="trust-document">${ps.map(p=>`<p>${esc(p)}</p>`).join('')}</article><button class="trust-doc-back" type="button" data-legal-home>${esc(t('back'))}</button>`}
  function about(){const rows=[[t('versionLabel'),`V${VERSION}`],[t('studio'),STUDIO],[t('primary'),t('primaryV')],[t('benchmark'),t('benchmarkV')],[t('hosting'),t('hostingV')],[t('privacyModel'),t('privacyV')],[t('sourceStatus'),t('sourceV')]];return `<section class="trust-hero trust-about-hero"><img class="velnox-brand-mark velnox-brand-mark--trust-about" src="assets/velnox-mark.svg" alt="" aria-hidden="true"><span>${esc(t('aboutEye'))}</span><h1>${esc(t('aboutTitle'))}</h1><p>${esc(t('aboutLead'))}</p></section><div class="trust-about-grid">${rows.map(([a,b])=>`<article><small>${esc(a)}</small><strong>${esc(b)}</strong></article>`).join('')}</div><p class="trust-center-note">${esc(t('aboutNote'))}</p><p class="trust-copyright">© 2026 Benedict Interactive · ${L()==='th'?'สงวนสิทธิ์ตามกฎหมาย':'All rights reserved.'}</p>`}
  function render(view,a=''){S.view=view;const c=ensureRoot().querySelector('#trustContent');c.innerHTML=view==='transparency'?transparency(a):view==='support'?support(a):view==='help'?help(a):view==='legal'?legalHome():view.startsWith('legal:')?legalDoc(view.split(':')[1]):about();c.scrollTop=0;if(a)requestAnimationFrame(()=>c.querySelector(`#trust-${a}`)?.scrollIntoView({block:'start'}))}
  function open(view='about',a=''){show();render(view,a);setTimeout(()=>S.root?.querySelector('#trustBack')?.focus({preventScroll:true}),20)}
  function external(url){document.getElementById('trustExternalConfirm')?.remove();const b=document.createElement('div');b.id='trustExternalConfirm';b.className='trust-modal-backdrop';b.innerHTML=`<div class="trust-modal"><span>↗</span><h2>${esc(t('externalTitle'))}</h2><p>${esc(t('externalBody'))}</p><div><button data-ext-cancel>${esc(t('cancel'))}</button><button class="primary" data-ext-go>${esc(t('cont'))}</button></div></div>`;document.body.appendChild(b);b.querySelector('[data-ext-cancel]').onclick=()=>b.remove();b.querySelector('[data-ext-go]').onclick=()=>{b.remove();const w=window.open(url,'_blank','noopener,noreferrer');if(!w)location.href=url}}
  async function rootClick(e){const x=e.target.closest('[data-external]');if(x){external(x.dataset.external);return}const l=e.target.closest('[data-legal-doc]');if(l){render(`legal:${l.dataset.legalDoc}`);return}if(e.target.closest('[data-legal-home]')){render('legal');return}if(e.target.closest('[data-copy-report]')){const f=document.getElementById('trustFeedbackForm'),m=document.getElementById('trustMessage')?.value||'';if(!m.trim()){toast(t('required'));return}toast(await copyText(reportBody(f.dataset.type,m,document.getElementById('trustIncludeDiagnostics')?.checked))?t('copied'):t('copyFail'))}}
  document.addEventListener('submit',e=>{const f=e.target.closest('#trustFeedbackForm');if(!f)return;e.preventDefault();const m=document.getElementById('trustMessage')?.value||'';if(!m.trim()){toast(t('required'));return}const body=reportBody(f.dataset.type,m,document.getElementById('trustIncludeDiagnostics')?.checked),sub=f.dataset.type==='report'?'Velnox — Problem Report':'Velnox — Feedback';location.href=`mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent(sub)}&body=${encodeURIComponent(body)}`});
  document.addEventListener('keydown',e=>{if(!S.root?.hidden&&e.key==='Escape'){e.preventDefault();close()}});
  function refresh(){if(!S.built)return;const groups=[...document.querySelectorAll('#settingsSheet .trust-settings-group')],titles=[t('exp'),t('privacy'),t('measurement'),t('support'),t('help'),t('legal'),t('aboutGroup')];groups.forEach((g,i)=>{if(g.querySelector('h4'))g.querySelector('h4').textContent=titles[i]});const map={trustLocalDataBtn:['localData','localDataSub'],trustMethodBtn:['method','methodSub'],trustScoreBtn:['score','scoreSub'],trustLocationBtn:['location','locationSub'],trustKofiBtn:['worldwide','worldwideSub'],trustPromptPayBtn:['thailand','thailandSub'],trustReportBtn:['report','reportSub'],trustFeedbackBtn:['feedback','feedbackSub'],trustDiagnosticsBtn:['diagnostics','diagnosticsSub'],trustLegalBtn:['legalCenter','legalSub'],trustAboutBtn:['about','aboutSub']};for(const[id,[a,b]]of Object.entries(map)){const n=document.getElementById(id);if(n){n.querySelector('strong').textContent=t(a);n.querySelector('small').textContent=t(b)}}const m=document.querySelector('.trust-motion-row');if(m){m.querySelector('b').textContent=t('motion');m.querySelector('small').textContent=t('motionSub');[t('system'),t('full'),t('reduced')].forEach((v,i)=>{if(m.querySelectorAll('option')[i])m.querySelectorAll('option')[i].textContent=v})}const note=document.querySelector('.trust-settings-note');if(note)note.textContent=t('supportNote');const foot=document.querySelector('.trust-legal-foot');if(foot)foot.textContent=t('legalFoot');if(S.root&&!S.root.hidden)render(S.view)}
  ['langTh','langEn','sheetTh','sheetEn'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>setTimeout(refresh,50)));
  function init(){buildSettings();if(!S.built)setTimeout(buildSettings,120);let m='system';try{m=localStorage.getItem(MOTION_KEY)||'system'}catch{}applyMotion(m)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  window.VelnoxTrust=Object.freeze({version:VERSION,legalVersion:LEGAL_VERSION,open,close,diagnostics});
})();
